version: 2.1

jobs:
  main:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - run:
          name: "Shim directory before install"
          command: "ls -lah /home/circleci/.pyenv/shims/"
      - restore_cache:
          keys:
            - cache-1
      # - run:
      #     name: "which pip is invoked"
      #     command: "which pip"
      # - run:
      #     name: "install flake8"
      #     command: "pip install flake8"
      # - save_cache:
      #     key: cache-1
      #     paths:
      #       - /home/circleci/.pyenv/shims/
      - run:
          name: "Shim directory after install"
          command: "ls -lah /home/circleci/.pyenv/shims/"

workflows:
  say-hello-workflow:
    jobs:
      - main
