version: 2.0

jobs:
  main:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: "Shim directory before install"
          command: "ls -lah /home/circleci/.pyenv/shims/"
      - restore_cache:
          keys:
            - cache-v2-{{ checksum "requirements.txt" }}
      - run: pip install -r requirements.txt
      - save_cache:
          key: cache-v2-{{ checksum "requirements.txt" }}
          paths:
            - /home/circleci/.pyenv/versions/3.9.6/lib/python3.9/site-packages
            - /home/circleci/.pyenv/shims
      - run:
          name: "Shim directory after install"
          command: "ls -lah /home/circleci/.pyenv/shims/"

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - main