version: 2.0

jobs:
  main:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: "Shim directory before install"
          command: "ls -lah /home/circleci/.pyenv/shims/"
      - run:
          name: "versions directory before install"
          command: "ls -lah /home/circleci/.pyenv/versions/ && ls -lah /home/circleci/.pyenv/versions/3.9.6/bin/"
      - restore_cache:
          keys:
            - cache-v4-{{ checksum "requirements.txt" }}
      - run: pip install -r requirements.txt
      - save_cache:
          key: cache-v4-{{ checksum "requirements.txt" }}
          paths:
            - /home/circleci/.pyenv/versions/
      - run:
          name: "Shim directory after install"
          command: "ls -lah /home/circleci/.pyenv/shims/"
      - run:
          name: "versions directory after install"
          command: "ls -lah /home/circleci/.pyenv/versions/ && ls -lah /home/circleci/.pyenv/versions/3.9.6/bin/"
      - run:
          name: "attempt to run flake"
          command: "python -m flake8 nonogram_solver"

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - main